language: cpp
dist: trusty
sudo: false
os: linux

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-6
      - g++-6-multilib
      - linux-libc-dev:i386
      - ninja-build

env:
  - CONFIGURATION=Debug
  - CONFIGURATION=Release

compiler:
  - clang
  - gcc

before_install:
  - if [ "${CC}" = "gcc" ]; then export CC=gcc-6 CXX=g++-6 CMAKE_AR=gcc-6-ar; else export CMAKE_AR=ar; fi

script:
  - mkdir build
  - cd build
  - cmake -G Ninja -DCMAKE_BUILD_TYPE="${CONFIGURATION}" -DCMAKE_AR="${CMAKE_AR}" ..
  - ninja
